apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "dashFrontend" . }}
  namespace: ultratone-dash
spec:
  hostnames:
  - {{ .Values.domainsNpaths.frontend.url }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: tls-gateway
    namespace: ultratone
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "dashFrontend" . }}
      port: 80
      weight: 1
    filters:
    - requestHeaderModifier:
        add:
        - name: X-Forwarded-For
          value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /payments
  - backendRefs:
    - group: ""
      kind: Service
      name: dash-backend
      port: 80
    filters:
    - requestHeaderModifier:
        add:
        - name: X-Forwarded-For
          value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /swagger
  - backendRefs:
    - group: ""
      kind: Service
      name: dash-backend
      port: 80
    filters:
    - requestHeaderModifier:
        add:
        - name: X-Forwarded-For
          value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /endpoints
  - backendRefs:
    - group: ""
      kind: Service
      name: dash-backend
      port: 80
    filters:
    - requestHeaderModifier:
        add:
        - name: X-Forwarded-For
          value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /hub
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "dashFrontend" . }}
      port: 80
    filters:
    - requestHeaderModifier:
        add:
        - name: X-Forwarded-For
          value: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
      type: RequestHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
