version: '3.4'

services:
  admin.api:
    image: ${DOCKER_REGISTRY-}payment.admin.api
    container_name: payment_admin_api
    build:
      context: .
      dockerfile: src/Service/Admin.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DB_APP_HOST=${DB_APP_HOST}
      - DB_APP_PORT=${DB_APP_PORT}
      - DB_APP_NAME=${DB_APP_NAME}
      - DB_APP_USER=${DB_APP_USER}
      - DB_APP_PASS=${DB_APP_PASS}
      - DB_INIT=${DB_INIT}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PFX_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PFX_PASS}
    ports:
      - "127.0.0.1:5000:80"
      - "127.0.0.1:5001:443"
    depends_on:
      mysql:
        condition: service_healthy
  
  
  
  payment.api:
    image: ${DOCKER_REGISTRY-}payment.api
    container_name: payment_api
    build:
      context: .
      dockerfile: src/Service/Payment.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DB_APP_HOST=${DB_APP_HOST}
      - DB_APP_PORT=${DB_APP_PORT}
      - DB_APP_NAME=${DB_APP_NAME}
      - DB_APP_USER=${DB_APP_USER}
      - DB_APP_PASS=${DB_APP_PASS}
      - DB_INIT=${DB_INIT}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PFX_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PFX_PASS}
      
      #Paypal variables
      - PAYPAL_SANDBOX_CLIENT_ID=${PAYPAL_SANDBOX_CLIENT_ID}
      - PAYPAL_SANDBOX_CLIENT_SECRET=${PAYPAL_SANDBOX_CLIENT_SECRET}
      - PAYPAL_LIVE_CLIENT_ID=${PAYPAL_LIVE_CLIENT_ID}
      - PAYPAL_LIVE_CLIENT_SECRET=${PAYPAL_LIVE_CLIENT_SECRET}
      
      #billplz variables
      - BILLPLZ_SANDBOX_API_KEY=${BILLPLZ_SANDBOX_API_KEY}
      - BILLPLZ_SANDBOX_COL_ID=${BILLPLZ_SANDBOX_COL_ID}
      - BILLPLZ_SANDBOX_SIG_KEY=${BILLPLZ_SANDBOX_SIG_KEY}
      - BILLPLZ_API_KEY=${BILLPLZ_API_KEY}
      - BILLPLZ_COL_ID=${BILLPLZ_COL_ID}
      - BILLPLZ_SIG_KEY=${BILLPLZ_SIG_KEY}
      
      #stripe variables
      - STRIPE_SANDBOX_SECRET_KEY=${STRIPE_SANDBOX_SECRET_KEY}
      - STRIPE_SANDBOX_PUBLISHABLE_KEY=${STRIPE_SANDBOX_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      
      #global api for redirection variables
      - GLOBAL_PAYMENT_HOST=${GLOBAL_PAYMENT_HOST}
      - GLOBAL_PAYMENT_PORT=${GLOBAL_PAYMENT_PORT}
      - GLOBAL_PAYMENT_SCHEMA=${GLOBAL_PAYMENT_SCHEMA}
    ports:
      - "127.0.0.1:5002:80"
      - "127.0.0.1:5003:443"
    depends_on:
      mysql:
        condition: service_healthy


  global.api:
    image: ${DOCKER_REGISTRY-}global.mvc
    container_name: global_mvc
    build:
      context: .
      dockerfile: src/Service/Global.Mvc/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DB_APP_HOST=${DB_APP_HOST}
      - DB_APP_PORT=${DB_APP_PORT}
      - DB_APP_NAME=${DB_APP_NAME}
      - DB_APP_USER=${DB_APP_USER}
      - DB_APP_PASS=${DB_APP_PASS}
      - DB_INIT=${DB_INIT}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PFX_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PFX_PASS}
      
      #Paypal variables
      - PAYPAL_SANDBOX_CLIENT_ID=${PAYPAL_SANDBOX_CLIENT_ID}
      - PAYPAL_SANDBOX_CLIENT_SECRET=${PAYPAL_SANDBOX_CLIENT_SECRET}
      - PAYPAL_LIVE_CLIENT_ID=${PAYPAL_LIVE_CLIENT_ID}
      - PAYPAL_LIVE_CLIENT_SECRET=${PAYPAL_LIVE_CLIENT_SECRET}
      
      #billplz variables
      - BILLPLZ_SANDBOX_API_KEY=${BILLPLZ_SANDBOX_API_KEY}
      - BILLPLZ_SANDBOX_COL_ID=${BILLPLZ_SANDBOX_COL_ID}
      - BILLPLZ_SANDBOX_SIG_KEY=${BILLPLZ_SANDBOX_SIG_KEY}
      - BILLPLZ_API_KEY=${BILLPLZ_API_KEY}
      - BILLPLZ_COL_ID=${BILLPLZ_COL_ID}
      - BILLPLZ_SIG_KEY=${BILLPLZ_SIG_KEY}
      
      #stripe variables
      - STRIPE_SANDBOX_SECRET_KEY=${STRIPE_SANDBOX_SECRET_KEY}
      - STRIPE_SANDBOX_PUBLISHABLE_KEY=${STRIPE_SANDBOX_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "127.0.0.1:5004:80"
      - "127.0.0.1:5005:443"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: percona:latest
    container_name: percona_container
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_APP_PASS}
    volumes:
      - percona_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  percona_data:
