# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

	desc "Deploy a new version to the Google Play"
	 lane :deploy do |options|
      abbPath = "../build/app/outputs/bundle/"+options[:flavor]+"Release/app-"+options[:flavor]+"-release.aab"
      flags = "-Ptarget=lib/main_"+options[:flavor]+".dart"
      flavor = options[:flavor]
      track = "internal"
      if flavor=="prod"
        track = "production"
      end
      gradle(task: "clean bundle",
        flavor: flavor,
        flags: flags,
        build_type: "Release",
        task: "bundle"
      )

      upload_to_play_store(
          "track": track,
          "aab": abbPath,
          "skip_upload_changelogs": true,
          "skip_upload_screenshots": true,
          "skip_upload_metadata": true,
          "skip_upload_images": true
      )
	 end
end