{{ if .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{ if .Values.deployment.container.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.deployment.container.pullSecrets.name }}
      {{ end }}
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.container.image.name }}:{{ .Values.deployment.container.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}

          {{ if .Values.deployment.container.env }}
          env:
            {{ toYaml .Values.deployment.container.env | nindent 10 }}
          {{ end }}

{{ end }}