{{ if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc  }} 
  username: {{ .Values.secret.username | b64enc | default }} 
{{ end }}