{{ if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.port }}
      nodePort: {{ .Values.service.nodePort }}
{{ end }}