//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appstract.Front.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CloudSimCardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CloudSimCardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appstract.Front.Application.Common.Resources.CloudSimCardResource", typeof(CloudSimCardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your country and carrier below.
        /// </summary>
        public static string ChooseCountryCarrier {
            get {
                return ResourceManager.GetString("ChooseCountryCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Payment Method.
        /// </summary>
        public static string ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred mobile number.
        /// </summary>
        public static string ChooseYourPreferredMobileNumber {
            get {
                return ResourceManager.GetString("ChooseYourPreferredMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred type of port.
        /// </summary>
        public static string ChooseYourPreferredType {
            get {
                return ResourceManager.GetString("ChooseYourPreferredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud SIM Card.
        /// </summary>
        public static string CloudSimCard {
            get {
                return ResourceManager.GetString("CloudSimCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country &amp; Carrier.
        /// </summary>
        public static string CountryAndCarrier {
            get {
                return ResourceManager.GetString("CountryAndCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country &amp; Carrier..
        /// </summary>
        public static string CountryCarrier {
            get {
                return ResourceManager.GetString("CountryCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated Port.
        /// </summary>
        public static string DedicatedPort {
            get {
                return ResourceManager.GetString("DedicatedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always active SIM card.
        /// </summary>
        public static string DedicatedPortDescription1 {
            get {
                return ResourceManager.GetString("DedicatedPortDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited activation time.
        /// </summary>
        public static string DedicatedPortDescription2 {
            get {
                return ResourceManager.GetString("DedicatedPortDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time setup fee of {0}.
        /// </summary>
        public static string DedicatedPortDescription3 {
            get {
                return ResourceManager.GetString("DedicatedPortDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount (Invited).
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Call Fee.
        /// </summary>
        public static string DomesticCallFee {
            get {
                return ResourceManager.GetString("DomesticCallFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic SMS Fee.
        /// </summary>
        public static string DomesticSMSFee {
            get {
                return ResourceManager.GetString("DomesticSMSFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string LoadingBarTitle {
            get {
                return ResourceManager.GetString("LoadingBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Numbers.
        /// </summary>
        public static string MobileNumbers {
            get {
                return ResourceManager.GetString("MobileNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Fee.
        /// </summary>
        public static string MonthlyFee {
            get {
                return ResourceManager.GetString("MonthlyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Range.
        /// </summary>
        public static string NumberRange {
            get {
                return ResourceManager.GetString("NumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number selected.
        /// </summary>
        public static string NumberSelected {
            get {
                return ResourceManager.GetString("NumberSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only.
        /// </summary>
        public static string Only {
            get {
                return ResourceManager.GetString("Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Currency.
        /// </summary>
        public static string OriginalCurrency {
            get {
                return ResourceManager.GetString("OriginalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Setup Fee.
        /// </summary>
        public static string PortSetupFee {
            get {
                return ResourceManager.GetString("PortSetupFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Number.
        /// </summary>
        public static string SearchNumber {
            get {
                return ResourceManager.GetString("SearchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country &amp; Carrier.
        /// </summary>
        public static string SelectCountryCarrier {
            get {
                return ResourceManager.GetString("SelectCountryCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mobile Number.
        /// </summary>
        public static string SelectMobileNumber {
            get {
                return ResourceManager.GetString("SelectMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type &amp; Period.
        /// </summary>
        public static string SelectTypePeriod {
            get {
                return ResourceManager.GetString("SelectTypePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Port.
        /// </summary>
        public static string SharedPort {
            get {
                return ResourceManager.GetString("SharedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active only on demand.
        /// </summary>
        public static string SharedPortDescription1 {
            get {
                return ResourceManager.GetString("SharedPortDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Free Activation Time Slot (Each 15 minutes) during one month.
        /// </summary>
        public static string SharedPortDescription2 {
            get {
                return ResourceManager.GetString("SharedPortDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €1 per additional Activation Time Slot.
        /// </summary>
        public static string SharedPortDescription3 {
            get {
                return ResourceManager.GetString("SharedPortDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim Setup Fee.
        /// </summary>
        public static string SimSetupFee {
            get {
                return ResourceManager.GetString("SimSetupFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There’s no available sim card to show..
        /// </summary>
        public static string ThereIsNoAvailableSimCard {
            get {
                return ResourceManager.GetString("ThereIsNoAvailableSimCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total based on payment method.
        /// </summary>
        public static string TotalBasedOnPaymentMethod {
            get {
                return ResourceManager.GetString("TotalBasedOnPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total checkout.
        /// </summary>
        public static string TotalCheckout {
            get {
                return ResourceManager.GetString("TotalCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type..
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &amp; Period.
        /// </summary>
        public static string TypePeriod {
            get {
                return ResourceManager.GetString("TypePeriod", resourceCulture);
            }
        }
    }
}
