//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appstract.Front.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubMenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SubMenuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appstract.Front.Application.Common.Resources.SubMenuResource", typeof(SubMenuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Credit.
        /// </summary>
        public static string BuyCredit {
            get {
                return ResourceManager.GetString("BuyCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        public static string Callback {
            get {
                return ResourceManager.GetString("Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call History.
        /// </summary>
        public static string CallHistory {
            get {
                return ResourceManager.GetString("CallHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Service.
        /// </summary>
        public static string CallService {
            get {
                return ResourceManager.GetString("CallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud SIM Card.
        /// </summary>
        public static string CloudSimCard {
            get {
                return ResourceManager.GetString("CloudSimCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVR/Queue.
        /// </summary>
        public static string IVRQueue {
            get {
                return ResourceManager.GetString("IVRQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Phone Number.
        /// </summary>
        public static string LinkedPhoneNumber {
            get {
                return ResourceManager.GetString("LinkedPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase History.
        /// </summary>
        public static string PurchaseHistory {
            get {
                return ResourceManager.GetString("PurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Dial.
        /// </summary>
        public static string SpeedDial {
            get {
                return ResourceManager.GetString("SpeedDial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Top-Up.
        /// </summary>
        public static string VoucherTopup {
            get {
                return ResourceManager.GetString("VoucherTopup", resourceCulture);
            }
        }
    }
}
