apiVersion: v1
baseDomain: maxtld.dev
metadata:
  name: os-rg1

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 2

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  vsphere:
    vcenter: 'vcenterFQDN or ip address'
    username: 'administrator@vsphere.local or a user with appropriate permission'
    password: '...'
    datacenter: 'vsphere datacenter name'
    defaultDatastore: 'datastore name'

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}' 
sshKey: 'ssh-ed25519 AAAA....  root@localhost.localdomain '
