parameters:
  - name: dotnetVersion
    type: string
  - name: nugetServiceConnectionName
    type: string

steps:

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: ' 6.7.0'

  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'
    inputs:
      nugetServiceConnectionNames: ${{ parameters.nugetServiceConnectionName }}

  - task: DotNetCoreCLI@2
    displayName: 'Build payment.sln'
    inputs:
      command: 'build'
      version: ${{ parameters.dotnetVersion }}
      projects: 'Payment.sln'
      


