parameters:
- name: chartPath
  type: string
- name: destination
  type: string
- name: chartName
  type: string
- name: gitlabUser
  type: string
- name: gitlabPass
  type: string
- name: gitlabChart
  type: string


steps:
# Ensure Helm
- task: HelmInstaller@1
  displayName: Helm installer
  inputs: 
    helmVersionToInstall: latest

# Pack
- task: HelmDeploy@0
  displayName: 'Helm package'
  inputs:
    command: package
    chartPath: '${{ parameters.chartPath }}'
    destination: '${{ parameters.destination }}'
    save: false
#    failOnStderr: true

# Publish
- task: Bash@3
  displayName: Publish to Gitlab
  inputs:
    targetType: 'inline'
    script: |
      cd ${{ parameters.destination }}
      curl --request POST --form 'chart=@${{ parameters.chartName }}' --user ${{ parameters.gitlabUser }}:${{ parameters.gitlabPass }} ${{ parameters.gitlabChart }}
